name: GitHub Secrets

on:
    workflow_dispatch:

jobs:
    deployment:
        runs-on: ubuntu-20.04
        steps:
            - name: Print Secret
              run: | 
                echo "TOPSECRET" : ${{ secrets.TOPSECRET }}
            
            - name: Print Secret as env
              run: | 
                echo "TOPSECRET : $APPSECRET"
              env: 
                APPSECRET: ${{ secrets.TOPSECRET }}


            - name: Print variable 
              run: | 
                echo "Variable : ${{ vars.TOP_VARIABLES }}"
                echo "Variable : ${{ vars.TOP_VARIABLE }}"